// src/views/CanvasListView.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useStorage } from '@/composables/useStorage'
import { getAnimationDuration } from '@/utils/timing'
import type { CanvasState } from '@/types'

const router = useRouter()

const { state, createCanvas, deleteCanvas } = useStorage()

const sortedCanvases = computed(() => {
  return [...state.value.canvases].sort((a, b) => {
    return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  })
})

const showCreateModal = ref(false)
const newCanvasName = ref('')
const createInputRef = ref<HTMLInputElement | null>(null)

const openCreateModal = () => {
  newCanvasName.value = ''
  showCreateModal.value = true
  setTimeout(() => {
    createInputRef.value?.focus()
  }, getAnimationDuration('FOCUS_DELAY'))
}

const handleCreate = () => {
  const name = newCanvasName.value.trim() || 'Novo Canvas'
  const canvasId = createCanvas(name)
  showCreateModal.value = false
  router.push({ name: 'canvas', params: { id: canvasId } })
}

const handleCreateKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    handleCreate()
  }
  if (e.key === 'Escape') {
    showCreateModal.value = false
  }
}

const canvasToDelete = ref<CanvasState | null>(null)

const confirmDelete = (canvas: CanvasState) => {
  canvasToDelete.value = canvas
}

const handleDelete = () => {
  if (canvasToDelete.value) {
    deleteCanvas(canvasToDelete.value.id)
    canvasToDelete.value = null
  }
}

const cancelDelete = () => {
  canvasToDelete.value = null
}

const handleSelect = (canvasId: string) => {
  router.push({ name: 'canvas', params: { id: canvasId } })
}

const formatDate = (dateString: string): string => {
  const date = new Date(dateString)
  return date.toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatRelativeDate = (dateString: string): string => {
  const date = new Date(dateString)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60))
  const diffDays = Math.floor(diffHours / 24)

  if (diffHours < 1) return 'Agora mesmo'
  if (diffHours < 24) return `${diffHours}h atras`
  if (diffDays < 7) return `${diffDays}d atras`

  return formatDate(dateString)
}

// Preview node colors
const previewNodeColors: Record<string, string> = {
  tweet: 'bg-accent-tweet',
  question: 'bg-accent-question',
  note: 'bg-amber-600'
}
</script>

<template>
  <div class="min-h-screen bg-gray-50" data-testid="canvas-list-view">
    <header class="flex items-center justify-between px-8 py-6 bg-white border-b border-gray-200">
      <div class="flex flex-col">
        <h1 class="text-xl font-bold text-gray-900">gyul</h1>
        <p class="text-sm text-gray-600">Explore tweets com IA</p>
      </div>

      <button
        type="button"
        class="flex items-center gap-2 px-6 py-2 bg-brand-500 text-white border-none rounded-lg text-sm font-medium cursor-pointer transition-colors duration-fast hover:bg-brand-600"
        data-testid="create-canvas-btn"
        @click="openCreateModal"
      >
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="12" y1="5" x2="12" y2="19" />
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
        Novo Canvas
      </button>
    </header>

    <main class="p-8 max-w-[1200px] mx-auto">
      <div v-if="sortedCanvases.length === 0" class="flex flex-col items-center justify-center py-16 text-center" data-testid="empty-state">
        <svg class="w-16 h-16 text-gray-400 mb-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path
            d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
          />
        </svg>
        <h2 class="text-lg font-semibold text-gray-900 mb-2">Nenhum canvas ainda</h2>
        <p class="text-gray-600 mb-6">Crie seu primeiro canvas para comecar a explorar</p>
        <button
          type="button"
          class="px-6 py-2 bg-brand-500 text-white border-none rounded-lg text-sm font-medium cursor-pointer hover:bg-brand-600"
          data-testid="create-first-canvas-btn"
          @click="openCreateModal"
        >
          Criar primeiro canvas
        </button>
      </div>

      <div v-else class="grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-6" data-testid="canvas-grid">
        <article
          v-for="canvas in sortedCanvases"
          :key="canvas.id"
          class="group bg-white border border-gray-200 rounded-lg p-4 cursor-pointer transition-all duration-fast hover:border-brand-500 hover:shadow-node-hover"
          :data-testid="`canvas-card-${canvas.id}`"
          @click="handleSelect(canvas.id)"
        >
          <div class="flex items-start justify-between mb-2">
            <h3 class="text-base font-semibold text-gray-900" data-testid="canvas-name">{{ canvas.name }}</h3>
            <button
              type="button"
              class="p-1 bg-transparent border-none text-gray-400 cursor-pointer opacity-0 transition-all duration-fast group-hover:opacity-100 hover:text-danger [.group:hover_&]:opacity-100"
              title="Deletar"
              data-testid="delete-canvas-btn"
              @click.stop="confirmDelete(canvas)"
            >
              <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path
                  d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                />
              </svg>
            </button>
          </div>

          <div class="flex gap-4 text-sm text-gray-600 mb-4">
            <span data-testid="canvas-node-count">
              {{ canvas.nodes.length }} nos
            </span>
            <span data-testid="canvas-date">
              {{ formatRelativeDate(canvas.updatedAt) }}
            </span>
          </div>

          <div class="relative h-20 bg-gray-50 rounded-lg overflow-hidden">
            <div
              v-for="(node, index) in canvas.nodes.slice(0, 3)"
              :key="node.id"
              :class="['absolute w-10 h-5 rounded opacity-60', (node.data?.type && previewNodeColors[node.data.type]) || 'bg-gray-400']"
              :style="{ left: `${20 + index * 30}%`, top: `${30 + index * 15}%` }"
            />
          </div>
        </article>
      </div>
    </main>

    <!-- Create Modal -->
    <div
      v-if="showCreateModal"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-modal"
      data-testid="create-modal"
      @click.self="showCreateModal = false"
    >
      <div class="bg-white rounded-lg p-6 w-full max-w-[400px] animate-fade-in">
        <h2 class="text-lg font-semibold mb-4">Novo Canvas</h2>

        <input
          ref="createInputRef"
          v-model="newCanvasName"
          type="text"
          placeholder="Nome do canvas"
          class="w-full px-4 py-2 border border-gray-200 rounded-lg text-base mb-6 focus:outline-none focus:border-brand-500"
          data-testid="canvas-name-input"
          @keydown="handleCreateKeydown"
        />

        <div class="flex justify-end gap-2">
          <button
            type="button"
            class="px-6 py-2 bg-gray-50 text-gray-600 border-none rounded-lg text-sm font-medium cursor-pointer transition-colors duration-fast hover:bg-gray-200"
            data-testid="cancel-create-btn"
            @click="showCreateModal = false"
          >
            Cancelar
          </button>
          <button
            type="button"
            class="px-6 py-2 bg-brand-500 text-white border-none rounded-lg text-sm font-medium cursor-pointer transition-colors duration-fast hover:bg-brand-600"
            data-testid="confirm-create-btn"
            @click="handleCreate"
          >
            Criar
          </button>
        </div>
      </div>
    </div>

    <!-- Delete Modal -->
    <div
      v-if="canvasToDelete"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-modal"
      data-testid="delete-modal"
      @click.self="cancelDelete"
    >
      <div class="bg-white rounded-lg p-6 w-full max-w-[400px] animate-fade-in">
        <h2 class="text-lg font-semibold mb-4">Deletar Canvas</h2>
        <p class="text-gray-600 mb-6">
          Tem certeza que deseja deletar <strong>"{{ canvasToDelete.name }}"</strong>? Esta acao nao
          pode ser desfeita.
        </p>

        <div class="flex justify-end gap-2">
          <button
            type="button"
            class="px-6 py-2 bg-gray-50 text-gray-600 border-none rounded-lg text-sm font-medium cursor-pointer transition-colors duration-fast hover:bg-gray-200"
            data-testid="cancel-delete-btn"
            @click="cancelDelete"
          >
            Cancelar
          </button>
          <button
            type="button"
            class="px-6 py-2 bg-danger text-white border-none rounded-lg text-sm font-medium cursor-pointer transition-colors duration-fast hover:bg-red-600"
            data-testid="confirm-delete-btn"
            @click="handleDelete"
          >
            Deletar
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/views/CanvasListView.tsx
import { useState } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { formatDistanceToNow } from 'date-fns'
import { useAppStore } from '../stores/appStore'
import { CreateCanvasModal } from '../components/CreateCanvasModal'
import { DeleteCanvasModal } from '../components/DeleteCanvasModal'
import { countShapesInSnapshot, formatShapeCount } from '../utils/canvasUtils'
import type { CanvasState } from '../types'

export function CanvasListView() {
  const navigate = useNavigate()
  const { state, createCanvas, deleteCanvas } = useAppStore()

  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [deleteModalState, setDeleteModalState] = useState<{
    open: boolean
    canvas: CanvasState | null
  }>({ open: false, canvas: null })

  const handleCreateCanvas = (name: string) => {
    const canvasId = createCanvas(name)
    navigate({ to: '/canvas/$id', params: { id: canvasId } })
  }

  const handleOpenCanvas = (canvasId: string) => {
    navigate({ to: '/canvas/$id', params: { id: canvasId } })
  }

  const handleDeleteClick = (canvas: CanvasState, e: React.MouseEvent) => {
    e.stopPropagation()
    setDeleteModalState({ open: true, canvas })
  }

  const handleConfirmDelete = () => {
    if (deleteModalState.canvas) {
      deleteCanvas(deleteModalState.canvas.id)
    }
  }

  const formatRelativeDate = (dateString: string) => {
    try {
      const date = new Date(dateString)
      return formatDistanceToNow(date, { addSuffix: true })
    } catch {
      return 'Unknown'
    }
  }

  const sortedCanvases = [...state.canvases].sort(
    (a, b) =>
      new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  )

  return (
    <div className="min-h-screen bg-[var(--gray-50)] p-8">
      <header className="mb-8 flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-[var(--gray-900)]">gyul</h1>
        {state.canvases.length > 0 && (
          <button
            onClick={() => setIsCreateModalOpen(true)}
            className="rounded-lg bg-[var(--color-tweet)] px-4 py-2 text-white transition-colors hover:bg-[var(--color-tweet)]/90"
            data-testid="new-canvas-button"
          >
            New Canvas
          </button>
        )}
      </header>

      {state.canvases.length === 0 ? (
        <div
          className="flex flex-col items-center justify-center py-16"
          data-testid="empty-state"
        >
          <p className="mb-4 text-[var(--gray-400)]">No canvases yet</p>
          <button
            onClick={() => setIsCreateModalOpen(true)}
            className="rounded-lg border-2 border-dashed border-[var(--gray-300)] px-6 py-3 text-[var(--gray-400)] transition-colors hover:border-[var(--color-tweet)] hover:text-[var(--color-tweet)]"
            data-testid="create-first-canvas-button"
          >
            Create your first canvas
          </button>
        </div>
      ) : (
        <div
          className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"
          data-testid="canvas-list"
        >
          {sortedCanvases.map((canvas) => (
            <article
              key={canvas.id}
              onClick={() => handleOpenCanvas(canvas.id)}
              className="group cursor-pointer rounded-xl border border-[var(--gray-300)] bg-white p-4 shadow-[var(--shadow-md)] transition-shadow hover:shadow-[var(--shadow-lg)]"
              data-testid="canvas-card"
              data-canvas-id={canvas.id}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1 min-w-0">
                  <h3
                    className="truncate font-medium text-[var(--gray-900)]"
                    data-testid="canvas-name"
                  >
                    {canvas.name}
                  </h3>
                  <p
                    className="mt-1 text-sm text-[var(--gray-400)]"
                    data-testid="canvas-shape-count"
                  >
                    {formatShapeCount(countShapesInSnapshot(canvas.snapshot))}
                  </p>
                  <p
                    className="mt-1 text-sm text-[var(--gray-400)]"
                    data-testid="canvas-date"
                  >
                    {formatRelativeDate(canvas.updatedAt)}
                  </p>
                </div>
                <button
                  onClick={(e) => handleDeleteClick(canvas, e)}
                  className="rounded p-1 text-[var(--gray-400)] opacity-0 transition-all hover:bg-[var(--color-error)]/10 hover:text-[var(--color-error)] group-hover:opacity-100"
                  aria-label={`Delete ${canvas.name}`}
                  data-testid="delete-canvas-button"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                    />
                  </svg>
                </button>
              </div>
            </article>
          ))}
        </div>
      )}

      {/* Create Canvas Modal */}
      <CreateCanvasModal
        open={isCreateModalOpen}
        onOpenChange={setIsCreateModalOpen}
        onCreateCanvas={handleCreateCanvas}
      />

      {/* Delete Canvas Modal */}
      <DeleteCanvasModal
        open={deleteModalState.open}
        onOpenChange={(open) =>
          setDeleteModalState((prev) => ({ ...prev, open }))
        }
        canvasName={deleteModalState.canvas?.name || ''}
        onConfirmDelete={handleConfirmDelete}
      />
    </div>
  )
}
