// src/components/ui/LoadingSpinner.vue
<script setup lang="ts">
/**
 * LoadingSpinner - Indicador de carregamento animado
 * 
 * Design System: Quiet UI
 * SVG spinner com animacao CSS.
 * Tamanho e cor configuraveis.
 * 
 * @example
 * <LoadingSpinner size="md" />
 * <LoadingSpinner size="lg" class="text-blue-500" />
 */

export interface Props {
  /** Tamanho do spinner */
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md'
})

const sizeClasses: Record<string, string> = {
  sm: 'w-4 h-4',
  md: 'w-6 h-6',
  lg: 'w-8 h-8'
}
</script>

<template>
  <svg
    :class="['animate-spin text-warning', sizeClasses[props.size]]"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    :data-size="props.size"
    data-testid="loading-spinner"
  >
    <circle
      class="opacity-20"
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      stroke-width="3"
    />
    <circle
      class="[stroke-dasharray:60] [stroke-dashoffset:45]"
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      stroke-width="3"
      stroke-linecap="round"
    />
  </svg>
</template>

// src/components/ui/LoadingSpinner.tsx
import type { HTMLAttributes } from 'react'

interface LoadingSpinnerProps extends HTMLAttributes<HTMLDivElement> {
  size?: number
  color?: string
}

/**
 * Animated loading spinner.
 * Uses CSS animation for smooth rotation.
 */
export function LoadingSpinner({
  size = 24,
  color = 'currentColor',
  className = '',
  ...props
}: LoadingSpinnerProps) {
  return (
    <div
      className={`inline-flex items-center justify-center ${className}`}
      data-testid="loading-spinner"
      {...props}
    >
      <svg
        className="animate-spin"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          className="opacity-25"
          cx="12"
          cy="12"
          r="10"
          stroke={color}
          strokeWidth="3"
        />
        <path
          className="opacity-75"
          fill={color}
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
        />
      </svg>
    </div>
  )
}
